# General plugin settings
general:
  # Whether to display the head count in the player list (scoreboard)
  display_score_in_player_list: false
  # Whether to log drop chance rolls to console (useful for debugging)
  log_rolls: false
  # Whether to broadcast when a player gets a head
  broadcast_head_drops: false
  # Whether to show kill count messages in chat
  show_kill_count: false
  # Whether to show head count messages in chat
  show_head_count: false
  # Whether to show periodic head collection summary in chat
  show_head_collection_summary: false
  # Whether to capitalize mob names in item names (e.g., 'zombie' becomes 'Zombie', 'zombie villager' becomes 'Zombie villager')
  capitalize_mob_names: true
  # Whether to disable custom lore to fix compatibility with claim plugins
  # When enabled, heads will appear as vanilla items without custom NBT data
  fix_claim_plugins: false
  # Minimum permission level required to receive head drop broadcasts (empty for all players)
  # Example: 'headhunter.notify' - only players with this permission will see broadcasts
  broadcast_permission: ''

# Looting enchantment settings
looting_enchantment:
  # Whether looting affects the drop rate of heads
  affects_drop_rate: false
  # Multiplies the drop rate like so: new_drop_rate = drop_rate * (1 + (looting_level * drop_rate_multiplier))
  # So if drop_rate_multiplier=0.1 and looting_level=3, then a drop rate of 0.002 becomes 0.002 * (1 + (0.3)) = 0.0026
  drop_rate_multiplier: 0.05
messages:
  # You may update/translate/colorize the messages that get broadcasted to players here. Make sure to include {PLAYER_NAME},
  # {MOB_NAME}, or any other non-color variables inside curly braces; otherwise, the default will be used. Customize the color
  # with {COLOR:_____} variables (see valid colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html).
  # An example spanish message:
  # head_drop: "{COLOR:DARK_GREEN}{PLAYER_NAME}{COLOR:GRAY} consiguió la cabeza de {COLOR:DARK_AQUA}{MOB_NAME}{COLOR:GRAY}."
  head_drop: "{COLOR:LIGHT_PURPLE}{PLAYER_NAME}{COLOR:GRAY} just got a {COLOR:LIGHT_PURPLE}{MOB_NAME}{COLOR:GRAY} head"
  kill_count: "{COLOR:AQUA}{PLAYER_NAME}{COLOR:GRAY} has killed {NUMBER} {COLOR:AQUA}{MOB_NAME}{COLOR:GRAY}'s"
  head_count: "{COLOR:AQUA}{PLAYER_NAME}{COLOR:GRAY} has received {NUMBER} {COLOR:AQUA}{MOB_NAME}{COLOR:GRAY} heads"
  heads: "{COLOR:AQUA}{PLAYER_NAME}{COLOR:GRAY} has received {NUMBER}/{TOTAL} heads: {COLOR:AQUA}{HEAD_LIST}{COLOR:GRAY}"
  command_errors:
    missing_mob_name: "You must provide a mob name (example: FROG_COLD)"
    invalid_mob_name: "That mob does not exist. Try '/mobs' to view a list of all mobs."
  head_lore:
    owner_statement: "{COLOR:YELLOW}Killed by {COLOR:LIGHT_PURPLE}{PLAYER_NAME}{COLOR:YELLOW}"
    secondary_statement: "{COLOR:GRAY}A mod by CrazyCranberry"